<a href="https://colab.research.google.com/github/Jashanpreet645/UCS712-Cognitive-Computing-Lab-/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question - 1

In [18]:
import pandas as pd
data = {
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["yes","no","no","yes","no","no","yes","no","no","no"],
    "Maritan status":['single','married','single','married','divorced','married','divorced','single','married','single'],
    "taxable income":['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
    "cheat":['no','no','no','no','yes','no','no','yes','no','yes']
}
df = pd.DataFrame(data)
print(df.head(10))

   Tid Refund Maritan status taxable income cheat
0    1    yes         single           125k    no
1    2     no        married           100k    no
2    3     no         single            70k    no
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes
8    9     no        married            75k    no
9   10     no         single            90k   yes

# Queston 2

In [19]:
print(f"0 row is \n{df.loc[0]},\n\n4 row is \n{df.loc[3]},\n\n7 row is \n{df.loc[6]},\n\n8 row is \n{df.loc[7]}")

0 row is
Tid                    1
Refund               yes
Maritan status    single
taxable income      125k
cheat                 no
Name: 0, dtype: object,

4 row is
Tid                     4
Refund                yes
Maritan status    married
taxable income       120k
cheat                  no
Name: 3, dtype: object,

7 row is
Tid                      7
Refund                 yes
Maritan status    divorced
taxable income        220k
cheat                   no
Name: 6, dtype: object,

8 row is
Tid                    8
Refund                no
Maritan status    single
taxable income       85k
cheat                yes
Name: 7, dtype: object

# Queston 3

In [20]:
print(f"3 to 7 row is \n{df.iloc[3:7]},\n\n4 to 8 row and 2 t 4 columns is \n{df.iloc[4:8,2:4]},\n\n7 row is \n{df.loc[6]},\n\n8 row is \n{df.iloc[:,1:3+1]}")

3 to 7 row is
   Tid Refund Maritan status taxable income cheat
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no,

4 to 8 row and 2 t 4 columns is
  Maritan status taxable income
4       divorced            95k
5        married            60k
6       divorced           220k
7         single            85k,

7 row is
Tid                      7
Refund                 yes
Maritan status    divorced
taxable income        220k
cheat                   no
Name: 6, dtype: object,

8 row is
  Refund Maritan status taxable income
0    yes         single           125k
1     no        married           100k
2     no         single            70k
3    yes        married           120k
4     no       divorced            95k
5     no        married            60k
6    yes       divorced           220k
7     no         single            85k
8     no        married            75k
9     no         single            90k

# Question 4

In [27]:
import pandas as pd
print("first five rows")
data = pd.read_csv("/content/iris.csv")
print(data.head(5))

print("last five rows")
print(data.tail(5))

first five rows
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
last five rows
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

# Queston 5

In [33]:
d1 = data.drop(columns=data.columns[3],index = 4)
# d1 = data.drop(index = 4)
print(d1)

     sepal_length  sepal_width  petal_length    species
0             5.1          3.5           1.4     setosa
1             4.9          3.0           1.4     setosa
2             4.7          3.2           1.3     setosa
3             4.6          3.1           1.5     setosa
5             5.4          3.9           1.7     setosa
..            ...          ...           ...        ...
145           6.7          3.0           5.2  virginica
146           6.3          2.5           5.0  virginica
147           6.5          3.0           5.2  virginica
148           6.2          3.4           5.4  virginica
149           5.9          3.0           5.1  virginica

[149 rows x 4 columns]

# Question 6

In [78]:
import pandas as pd
table = {
    "Employee_ID":[101,102,103,104,105],
    "Name":['alice','bob','charlie','diana','edward'],
    "Department":['HR','IT','IT','Marketing','Sales'],
    "Age":[29,34,41,28,38],
    "Salary":[50000,70000,65000,55000,60000],
    "Years_of_Experience":[4,8,10,3,12],
    "Joining_date":["2020-03-15",'2017-07-19','2013-06-01','2021-02-10','2010-11-25'],
    "Gender":['female','male','male','female','male'],
    "Bonus":[5000,7000,6000,4500,5000],
    "Rating":[4.5,4.0,3.8,4.7,3.5]
}

table = pd.DataFrame(table)
table.to_csv("Employee.csv",index = False)
d1 = pd.read_csv("/content/Employee.csv")
data = d1
data

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating
0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8
3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7
4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5

 Question 6.1

In [34]:
print(data.shape) #it is used to find total no. of rows and columns

(5, 10)

question 6.2

In [35]:
print(f"type of data in each column\n{data.dtypes}\n")
print(f"no of non-null count is\n{data.notnull().sum()}")

type of data in each column
Employee_ID              int64
Name                    object
Department              object
Age                      int64
Salary                   int64
Years_of_Experience      int64
Joining_date            object
Gender                  object
Bonus                    int64
Rating                 float64
dtype: object

no of non-null count is
Employee_ID            5
Name                   5
Department             5
Age                    5
Salary                 5
Years_of_Experience    5
Joining_date           5
Gender                 5
Bonus                  5
Rating                 5
dtype: int64

question 6.3

In [41]:
print("the short description is\n\n")
data.describe()

the short description is

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

question 6.4

In [36]:
print(f"First 5 rows\n{data.head(5)}\n\nlast 3 rows{data.tail(3)}")

First 5 rows
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    alice         HR   29   50000                    4
1          102      bob         IT   34   70000                    8
2          103  charlie         IT   41   65000                   10
3          104    diana  Marketing   28   55000                    3
4          105   edward      Sales   38   60000                   12

  Joining_date  Gender  Bonus  Rating
0   2020-03-15  female   5000     4.5
1   2017-07-19    male   7000     4.0
2   2013-06-01    male   6000     3.8
3   2021-02-10  female   4500     4.7
4   2010-11-25    male   5000     3.5

last 3 rows   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  charlie         IT   41   65000                   10
3          104    diana  Marketing   28   55000                    3
4          105   edward      Sales   38   60000                   12

  Joining_date  Gender  Bonus  Rating
2   2013-06-01    male   6000     3.8
3   2021-02-10  female   4500     4.7
4   2010-11-25    male   5000     3.5

question 6.5

In [51]:
average = data["Salary"].mean()
sum_of_all_bonus = data["Bonus"].sum()
min_age = data["Age"].min()
performance = data["Rating"].max()
print(f"average salary is = {average}")
print(f"total bonus paid to all employee = {sum_of_all_bonus}")
print(f"youngest employee age = {min_age}")
print(f"highest performance rating = {performance}")

average salary is = 60000.0
total bonus paid to all employee = 27500
youngest employee age = 28
highest performance rating = 4.7

Question 6.6

In [82]:
sorting = data.sort_values(by = "Salary")
sorting

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating
0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5,Excellent
3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7,Excellent
4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5,Average
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good

Question 6.7

In [83]:
def categorize_perform(rating):
  if(rating>=4.5):
    return "Excellent"
  elif(rating>=4.0 and rating<4.5):
    return "Good"
  else:
    return "Average"

data["performance rating"] = data["Rating"].apply(categorize_perform)
data

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating
0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5,Excellent
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average
3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7,Excellent
4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5,Average

Question 6.8

In [84]:
print(data.isnull().any().any())
print(data.columns[data.isnull().any()])

False
Index([], dtype='object')

Question 6.9

In [87]:
data = data.rename(columns = {"Employee_ID":"ID"})
data

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating
0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5,Excellent
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average
3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7,Excellent
4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5,Average

Question 6.10

In [90]:
filtering = data[(data["Years_of_Experience"]>5) & (data["Department"]=="IT")]
filtering

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average

Question 6.11

In [93]:
def deduction(salary):
  salary = salary - salary*0.1
  return salary

data["tax"] = data["Salary"].apply(deduction)
data

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating,tax
0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5,Excellent,45000.0
1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good,63000.0
2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average,58500.0
3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7,Excellent,49500.0
4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5,Average,54000.0

In [99]:
modified_data = data.to_csv("Modified employee.csv")
d2 = pd.read_csv("/content/Modified employee.csv")
d2

,Unnamed: 0,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_date,Gender,Bonus,Rating,performance rating,tax
0,0,101,alice,HR,29,50000,4,2020-03-15,female,5000,4.5,Excellent,45000.0
1,1,102,bob,IT,34,70000,8,2017-07-19,male,7000,4.0,Good,63000.0
2,2,103,charlie,IT,41,65000,10,2013-06-01,male,6000,3.8,Average,58500.0
3,3,104,diana,Marketing,28,55000,3,2021-02-10,female,4500,4.7,Excellent,49500.0
4,4,105,edward,Sales,38,60000,12,2010-11-25,male,5000,3.5,Average,54000.0